//! Generate Markdown from the real CLI definitions without compiling or running the gateway.

use std::io::{self, Write};

use clap::{ColorChoice, Command, CommandFactory};

// Compile the source modules directly so command definitions and validators cannot drift.
// Runtime-facing methods are deliberately unused by this documentation-only executable.
#[allow(dead_code)]
#[path = "../../agentic-server/src/agentic_cli.rs"]
mod agentic_cli;
#[allow(dead_code)]
#[path = "../../agentic-server/src/agentic_output.rs"]
mod agentic_output;

fn documentation_command(command: Command) -> Command {
    command
        .color(ColorChoice::Never)
        .term_width(88)
        .mut_args(|argument| argument.hide_env_values(true))
        .mut_subcommands(documentation_command)
}

fn write_command(command: &Command, path: &str, output: &mut impl Write) -> io::Result<()> {
    let mut rendered = command.clone().bin_name(path);
    writeln!(output, "## {path}\n\n```text")?;
    for line in rendered.render_long_help().to_string().trim().lines() {
        writeln!(output, "{}", line.trim_end())?;
    }
    writeln!(output, "```")?;
    for child in command
        .get_subcommands()
        .filter(|child| !child.is_hide_set() && child.get_name() != "help")
    {
        writeln!(output)?;
        write_command(child, &format!("{path} {}", child.get_name()), output)?;
    }
    Ok(())
}

fn write_reference(command: Command, output: &mut impl Write) -> io::Result<()> {
    let mut command = documentation_command(command);
    command.build();
    writeln!(output, "# Rust CLI reference\n")?;
    writeln!(
        output,
        "<!-- Generated by agentic-cli-docs. Edit the Rust CLI definitions, not this file. -->\n"
    )?;
    writeln!(
        output,
        "Generated from the CLI source in this checkout (package version **{}**). Use `agentic --help` or `agentic <command> --help` for your installed version.\n",
        env!("CARGO_PKG_VERSION")
    )?;
    writeln!(
        output,
        "The Rust command-line interface is `agentic ...`. Use it from a terminal to start the gateway, launch Codex or Claude Code, attach a harness to an existing gateway, and validate your configuration.\n"
    )?;
    writeln!(
        output,
        "Both `cargo install agentic-server` and `pip install agentic-api` install `agentic`. The PyPI package also includes the separate [Python launcher](python-cli.md), invoked as `agentic-api ...` or `python -m agentic_api ...`. Its commands, flags, and defaults differ from the Rust CLI.\n"
    )?;
    writeln!(
        output,
        "See [Python installation and workflows](../guides/python-installation.md) for package installation.\n"
    )?;
    write_command(&command, command.get_name(), output)
}

fn main() -> io::Result<()> {
    write_reference(agentic_cli::Cli::command(), &mut io::stdout().lock())
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Arg;

    #[test]
    fn reference_discovers_nested_commands_and_defaults() {
        let command = Command::new("agentic").subcommand(
            Command::new("new-command")
                .subcommand(Command::new("inspect").arg(Arg::new("limit").long("limit").default_value("42"))),
        );
        let mut output = Vec::new();
        write_reference(command, &mut output).expect("write reference");
        let markdown = String::from_utf8(output).expect("UTF-8 Markdown");
        assert!(markdown.contains("## agentic new-command inspect"));
        assert!(markdown.contains("--limit <limit>"));
        assert!(markdown.contains("[default: 42]"));
    }

    #[test]
    fn reference_hides_build_environment_values() {
        let command = Command::new("agentic").arg(Arg::new("path").long("path").env("PATH"));
        let mut output = Vec::new();
        write_reference(command, &mut output).expect("write reference");
        let markdown = String::from_utf8(output).expect("UTF-8 Markdown");
        assert!(markdown.contains("[env: PATH]"));
        if let Ok(path) = std::env::var("PATH") {
            assert!(!markdown.contains(&path));
        }
    }

    #[test]
    fn real_reference_includes_all_harness_commands_without_ansi_escapes() {
        let mut output = Vec::new();
        write_reference(agentic_cli::Cli::command(), &mut output).expect("write reference");
        let markdown = String::from_utf8(output).expect("UTF-8 Markdown");
        for name in [
            "run codex",
            "run claude",
            "harness codex",
            "harness claude",
            "serve",
            "validate",
        ] {
            assert!(markdown.contains(&format!("## agentic {name}\n")));
        }
        assert!(markdown.contains("--gateway-port"));
        assert!(!markdown.contains('\u{1b}'));
    }
}
