"""Generate Markdown from the source CLI, using only Python 3.11+ stdlib.

No wheel build is needed: temporary distribution metadata supplies the workspace
version required by agentic_api.__init__. Only the parser is constructed; no CLI
command, bundled executable, model, or vLLM runtime is invoked.
"""

from __future__ import annotations

import argparse
import sys
import tempfile
import tomllib
from functools import partial
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs/reference/python-cli.md"


def load_source_parser() -> tuple[argparse.ArgumentParser, str]:
    with (ROOT / "Cargo.toml").open("rb") as manifest:
        version = tomllib.load(manifest)["workspace"]["package"]["version"]
    original_path = sys.path[:]
    with tempfile.TemporaryDirectory(prefix="agentic-docs-") as directory:
        metadata = Path(directory) / "agentic_api.dist-info"
        metadata.mkdir()
        (metadata / "METADATA").write_text(
            f"Metadata-Version: 2.1\nName: agentic-api\nVersion: {version}\n", encoding="utf-8"
        )
        sys.path[:0] = [str(ROOT / "python"), directory]
        try:
            from agentic_api.cli import build_parser

            return build_parser(), version
        finally:
            sys.path[:] = original_path


def walk_parsers(parser: argparse.ArgumentParser):
    yield parser
    # argparse exposes subcommands through actions, not a public traversal API.
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            for child in dict.fromkeys(action.choices.values()):
                yield from walk_parsers(child)


def render_reference(parser: argparse.ArgumentParser, version: str) -> str:
    sections = [
        "# Python CLI reference",
        "<!-- Generated by scripts/generate_python_cli_docs.py. Edit the parser help, not this file. -->",
        f"Generated from the CLI source in this checkout (package version **{version}**). "
        "Use `agentic-api --help` or `agentic-api <command> --help` for your installed version.",
        "Agentic API provides two command-line interfaces (CLIs), both used from a terminal. "
        "The PyPI package includes both:",
        "- **Python launcher: `agentic-api ...`** — start the gateway with `agentic-api serve`, "
        "check your installation with `agentic-api doctor`, or inspect versions with `agentic-api version`. "
        "You can also use `python -m agentic_api ...`. This page documents the Python launcher.\n"
        "- **[Rust CLI](rust-cli.md): `agentic ...`** — run harnesses with `agentic run codex` or `agentic run claude`, "
        "or use `agentic serve` and `agentic validate`. It has its own commands and flags; "
        "run `agentic --help` for its command-line reference.",
        "See [Python installation and workflows](../guides/python-installation.md) for package installation, "
        "remote and local serving examples, and diagnostics.",
    ]
    for command in walk_parsers(parser):
        # Fixed width keeps generated output independent of the build terminal.
        command.formatter_class = partial(argparse.ArgumentDefaultsHelpFormatter, width=88)
        sections.extend([f"## {command.prog}", f"```text\n{command.format_help().rstrip()}\n```"])
    return "\n\n".join(sections) + "\n"


def main() -> int:
    options = argparse.ArgumentParser(description=__doc__)
    options.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    options.add_argument("--check", action="store_true", help="Fail if the output is missing or out of date")
    args = options.parse_args()
    parser, version = load_source_parser()
    markdown = render_reference(parser, version)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != markdown:
            print(f"{args.output} is out of date; run python3 scripts/generate_python_cli_docs.py", file=sys.stderr)
            return 1
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(markdown, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
